### ISSUE TITLE
Move off PlanetScale

### ISSUE THREAD

**Issue by aelew** [aelew/devterms#51]
PlanetScale is [sunsetting their hobby plan](https://planetscale.com/docs/concepts/hobby-plan-deprecation-faq), so I will unfortunately have to switch DevTerms' database from PlanetScale to something else. Currently planning on using Turso (SQLite)

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

**Comment by aelew** [comment]
> TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

Interesting, I've never heard about TiDB Serverless before. I'll take a closer look soon. Thanks for the suggestion!

**Comment by hooopo** [comment]
> > TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.
> 
> There doesn't seem to be support for Drizzle ORM, so unfortunately this won't be an option

Yes, it works with mysql2 driver, but not for edge/serverless current, https://github.com/drizzle-team/drizzle-orm/issues/1381

**Comment by aelew** [comment]
> Yes, it works with mysql2 driver, but not for edge/serverless current, [drizzle-team/drizzle-orm#1381](https://github.com/drizzle-team/drizzle-orm/issues/1381)

Yep, I'm hosting DevTerms on Vercel so it's using serverless functions

**Comment by AlexBlokh** [comment]
we will do the driver for TiDB

**Comment by deadcoder0904** [comment]
turso, astrodb, litefs are all great choices.

i've moved off to sqlite from planetscale & turso. works great.

if you're hosting this on vps, sqlite hosting would be easy. [a simple example with docker](https://github.com/deadcoder0904/easypanel-nextjs-sqlite) or [litefs is also good.](https://kentcdodds.com/blog/i-migrated-from-a-postgres-cluster-to-distributed-sqlite-with-litefs)

**Comment by aelew** [comment]
> turso, astrodb, litefs are all great choices.
> 
> i've moved off to sqlite from planetscale & turso. works great.
> 
> if you're hosting this on vps, sqlite hosting would be easy. [a simple example with docker](https://github.com/deadcoder0904/easypanel-nextjs-sqlite) or [litefs is also good.](https://kentcdodds.com/blog/i-migrated-from-a-postgres-cluster-to-distributed-sqlite-with-litefs)

I'm thinking of using [Xata](https://xata.io) (Postgres) since Drizzle has support for it now. Even though TiDB seems like a decent option, I don't think Drizzle will get TiDB driver support in time before PlanetScale retires their hobby plan on April 6.

Turso is great (I already moved a different project there), but I think Xata might be a better fit for this project. As for Astro DB, it's just a wrapper around Turso exclusively for Astro projects.

**Comment by deadcoder0904** [comment]
yeah, all choices are great. just hope that xata doesn't pull off planetscale in future. you can try self-hosting too if you wanna learn. its very easy to self-host & fun too. just need to spend $5/mo. i use https://easypanel.io as a panel with docker with sqlite. database backups are done using litestream. great for 95% of projects like this one.

while its true, astrodb is like turso. it isn't true that astrodb is exclusively for astro projects. only 1% people use astro lol so i don't think they'll target just astro users. its just a dbaas (database-as-a-service) so should work with any framework.
